export { escapeRouteOf, resolveEscape } from "./escape"
export type { EscapeOutcome } from "./escape"
export { createNavigation } from "./navigation"
export type { NavigationDeps } from "./navigation"
export { createInitialState, createInstance, paletteReducer } from "./reducer"
export type { PageInstance, PaletteAction, PaletteState } from "./types"
export { selectView } from "./view"
export type { Breadcrumb, PaletteView } from "./view"
